### ISSUE TITLE
does not run on HighSierra 10.13....

### ISSUE THREAD

**Issue by vsix27** [SamusAranX/MinimalMIDIPlayer#1]

**Comment by SamusAranX** [comment]
Please provide more details. I can't do anything if I don't know what's wrong.

**Comment by vsix27** [comment]
> Please provide more details. I can't do anything if I don't know what's wrong.

it does not load midi file, no errors, no messages, i uninstalled it, now using VLC without issues

**Comment by SamusAranX** [comment]
> Please provide more details. I can't do anything if I don't know what's wrong.
