### ISSUE TITLE
Project does not build!

### ISSUE THREAD

**Issue by Treata11** [SamusAranX/MinimalMIDIPlayer#12]
Greetings.
There's a missing file in the project `Sparkle.xcproj` ...
I thought maybe it's removed to reduce the project's size. So I added [Sparkle](https://github.com/sparkle-project/Sparkle?tab=readme-ov-file) as a dependency, but even that didn't solve the problem.

**Comment by SamusAranX** [comment]
Did you pull in the Sparkle submodule with something like `git submodule update --init`?

**Comment by Treata11** [comment]
No, I couldn't fix the issue with sparkle, so I downgraded to V1.11.0 :)
but thanks for the heads up.
