### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by vogler** [SamusAranX/MinimalMIDIPlayer#14]
Would be nice to be able to `brew install` this package.
(Especially since I didn't find any simple midi player with `brew search midi`.)

**Comment by SamusAranX** [comment]
I agree that this *would* be neat but it would involve making substantial changes to the update system so Sparkle and Homebrew don't get in each other's way. Probably not happening.

**Comment by vogler** [comment]
Why do you need to change anything? Just set `auto_updates true` for the cask. I have lots of apps installed via brew that update themselves via Sparkle.
