### ISSUE TITLE
Certain Instruments not playing after one loop

### ISSUE THREAD

**Issue by Xx-Henry-xX** [SamusAranX/MinimalMIDIPlayer#3]
I've been listening to R-Type Stage 1 MIDI on https://vgmusic.com/music/console/nec/tg16/ but after playing through the whole file once, replaying it mutes some instruments. (Significant in 0:14 of the said MIDI) Changing to other soundfont or reopening solves the problem only for the first loop after said actions.
I think it could be just AVMIDIPlayer issue.

**Comment by SamusAranX** [comment]
Hi!
I was able to reproduce the issue, but it seems to indeed be an issue with AVMIDIPlayer itself. I'll see what I can do about this. 

Don't hold your breath though. :/
