### ISSUE TITLE
Certain Soundfonts not playing properly

### ISSUE THREAD

**Issue by jkrosado** [SamusAranX/MinimalMIDIPlayer#4]
Certain soundfonts echo while playing, almost as if it was generated by the software, as it sounds natural, like the kind of echo Audacity produces, and one downright doesn't play anything, and makes loud crackling noises.

**Comment by SamusAranX** [comment]
Sadly, I can't do anything about the echo, that's just how the macOS MIDI system works. 😐

Do you have an example for soundfonts that don't play or make crackling noises?

**Comment by jkrosado** [comment]
> Sadly, I can't do anything about the echo, that's just how the macOS MIDI system works. 😐
> 
> Do you have an example for soundfonts that don't play or make crackling noises?

sorry for late response, the crackling comes from sf2 files designed for other platforms (wii, 3ds, etc.)

**Comment by SamusAranX** [comment]
Can you upload an example file? To my knowledge, none of these platforms actually *use* SF2 files, so these are most likely made by other people using sounds extracted from those platforms.

**Comment by jkrosado** [comment]
> Can you upload an example file? To my knowledge, none of these platforms actually _use_ SF2 files, so these are most likely made by other people using sounds extracted from those platforms.

the crackling is not related to MMP as i recently found out. they are extracted from proprietary files which have features that normal MIDIs don’t. the noise is the midi controller trying to interpret them as notes and fails to do so.
