### ISSUE TITLE
Any plans to allow saving the overridden Soundfontby default?

### ISSUE THREAD

**Issue by briantully** [SamusAranX/MinimalMIDIPlayer#5]
First off, thanks for developing this much needed tool! 

I was wondering if you had any plans to allow a user to override the Soundfont by default and save that within a global setting? For example I much prefer the Arachno Soundfont over the default, but every time I open a MIDI file I have to manually check "Override" and set the soundfont. Thankfully I don't have to locate it every time as it appears under "recent soundfonts", but I think it would be awesome if I could just set it once and for MinimalMIDIPlayer to retain that setting globally.

Thanks again!

**Comment by SamusAranX** [comment]
I didn't have any plans for this, but it's a good suggestion. If nothing goes catastrophically wrong, it'll be in the next update.

**Comment by SamusAranX** [comment]
Just a small update: It's implemented and mostly works, but I'm waiting for the final release of Big Sur to hopefully fix a few bugs that I think are OS bugs.
![image](https://user-images.githubusercontent.com/676069/98414806-57712b00-207c-11eb-94d6-010785d432d8.png)

**Comment by briantully** [comment]
Wow, this looks great! Thanks so much for considering this. I look forward to it :)

**Comment by SamusAranX** [comment]
Good news!

The feature's live now: https://github.com/SamusAranX/MinimalMIDIPlayer/releases/tag/v1.12-final

**Comment by briantully** [comment]
Thanks. I'm still on Mojave though :(
