### ISSUE TITLE
Repeat Button

### ISSUE THREAD

**Issue by copperisland** [SamusAranX/MinimalMIDIPlayer#7]
Not sure how easy/difficult it is to implement, but I think the app would be even more useful if you could repeat a song by having a repeat button similar to Apple Music/Spotify etc. 🔁/🔂  Other than that I think the app is pretty neat! 😄

**Comment by SamusAranX** [comment]
Hi and sorry for the late reply!
I'll add this to the app once I have the time.

**Comment by SamusAranX** [comment]
v1.13 adds a Loop menu item. The app should automatically update, but if it doesn't for whatever reason, the update can be found here: https://github.com/SamusAranX/MinimalMIDIPlayer/releases/tag/v1.13

**Comment by copperisland** [comment]
Works great thanks!
