### ISSUE TITLE
extreme reverb on some soundfonts

### ISSUE THREAD

**Issue by jkrosado** [SamusAranX/MinimalMIDIPlayer#8]
there is extreme reverb and echo on certain soundfonts _and midis**,_ sometimes even the default one. it doesn't appear in similar apps like miditrail. is this a midi device issue?

**here's an [example midi](https://drive.google.com/file/d/1nbYzp8VgtCL0QyQgXWtckI3AaW4BEx7V/view)

**Comment by SamusAranX** [comment]
That's a macOS shortcoming, I'm afraid. If you're comfortable with the terminal, you can use this script I wrote to generate new MIDI files with the reverb forced off: https://gist.github.com/SamusAranX/26e2653ffade956f3e531d7aa2666ef0
