### ISSUE TITLE
Is it possible to record the output?

### ISSUE THREAD

**Issue by muro** [SamusAranX/MinimalMIDIPlayer#9]
Thanks for a nice midi player, use it all the time now. Is it possible to record the output to a file instead of sending it through speakers by chance?

**Comment by muro** [comment]
I realized I can use BlackHole and QuickTime player. Sorry to bother.

https://github.com/ExistentialAudio/BlackHole

**Comment by SamusAranX** [comment]
Alternatively, you can use the Bounce feature under File -> Bounce or by pressing CMD + B.
